name: react-router-aws-lambda

services:
  app:
    platform: linux/arm64
    build:
      context: .
      dockerfile: site/Dockerfile
      target: app
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: "production"
      PORT: "8080"
  lambda:
    platform: linux/arm64
    build:
      context: .
      dockerfile: site/Dockerfile
      target: lambda-web-adapter
    ports:
      - "9090:9090"
    environment:
      NODE_ENV: "production"
      PORT: "9090"
      AWS_LAMBDA_EXEC_WRAPPER: "/opt/bootstrap"
      AWS_LWA_ENABLE_COMPRESSION: "true"
      AWS_LWA_INVOKE_MODE: "response_stream"
