name: react-router-aws-lambda

services:
  app:
    build:
      context: .
      dockerfile: site/Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: "production"
      PORT: "8080"
